/**
 * VIGILAX — Evidence Package Generator
 * Produces structured evidence packages for regulatory filing, law enforcement, and legal action.
 * Output: JSON manifest + HTML report (chain of custody compliant).
 */

'use strict';

const crypto = require('crypto');

// ── Chain of custody hash ────────────────────────────────────────────────────

function hashEvidence(data) {
  return crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex');
}

// ── Evidence package builder ─────────────────────────────────────────────────

/**
 * buildEvidencePackage(scanResult, metadata)
 * scanResult: output from any fraud engine (click, review, influencer, ad, gov)
 * metadata: { case_id, investigator, client_name, client_contact, notes }
 */
function buildEvidencePackage(scanResult, metadata = {}) {
  const packageId = `VX-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
  const generatedAt = new Date().toISOString();
  const evidenceHash = hashEvidence(scanResult);

  const pkg = {
    package_id: packageId,
    generated_at: generatedAt,
    evidence_hash: evidenceHash,  // SHA-256 of raw scan data
    schema_version: '2.0',

    chain_of_custody: {
      collector: 'VIGILAX Sentinel Automated System',
      collection_method: 'Automated algorithmic analysis',
      collection_timestamp: generatedAt,
      hash_algorithm: 'SHA-256',
      evidence_integrity_hash: evidenceHash,
      chain: [
        {
          step: 1,
          action: 'Data collection',
          actor: 'VIGILAX Engine',
          timestamp: scanResult.analyzed_at || generatedAt,
          hash: evidenceHash,
        },
        {
          step: 2,
          action: 'Evidence package generated',
          actor: metadata.investigator || 'VIGILAX Automated',
          timestamp: generatedAt,
          hash: hashEvidence({ packageId, evidenceHash, generatedAt }),
        },
      ],
    },

    case_information: {
      case_id: metadata.case_id || packageId,
      investigator: metadata.investigator || 'Francisco Holdings Inc.',
      client_name: metadata.client_name || null,
      client_contact: metadata.client_contact || null,
      jurisdiction: metadata.jurisdiction || 'Ontario, Canada',
      notes: metadata.notes || null,
    },

    fraud_summary: {
      engine: scanResult.engine,
      verdict: scanResult.verdict,
      risk_score: scanResult.risk_score,
      severity: scanResult.severity,
      analyzed_at: scanResult.analyzed_at,
      total_findings: (scanResult.findings || []).length,
      critical_findings: (scanResult.findings || []).filter(f => f.severity === 'CRITICAL').length,
      high_findings: (scanResult.findings || []).filter(f => f.severity === 'HIGH').length,
      recommended_action: scanResult.recommended_action,
    },

    findings: (scanResult.findings || []).map((f, i) => ({
      finding_number: i + 1,
      ...f,
      evidence_items: (f.evidence ? (Array.isArray(f.evidence) ? f.evidence : [f.evidence]) : []).length,
    })),

    raw_evidence: scanResult,

    regulatory_context: getRegulatoryContext(scanResult.engine, metadata.jurisdiction),

    disclaimer: 'This evidence package is generated by VIGILAX automated analysis software. It is intended to assist investigators and legal counsel. All findings should be independently verified by qualified professionals before use in legal proceedings. Francisco Holdings Inc. makes no representations regarding the admissibility of automated evidence in any jurisdiction.',
  };

  return pkg;
}

// ── Regulatory context per engine ────────────────────────────────────────────

function getRegulatoryContext(engine, jurisdiction = 'Ontario, Canada') {
  const contexts = {
    click_fraud: {
      relevant_laws: ['Competition Act (Canada) s.74.01 — deceptive marketing', 'Criminal Code s.380 — fraud over $5,000'],
      reporting_bodies: ['Competition Bureau Canada (competitionbureau.gc.ca)', 'Google Ads Invalid Traffic refund process', 'Meta Ad Credits claim process'],
      standard_refs: ['MRC (Media Rating Council) Invalid Traffic Guidelines', 'TAG (Trustworthy Accountability Group) Certified Against Fraud'],
      evidence_required: ['Click log exports from ad platform', 'IP geolocation data', 'Time-stamped session recordings'],
    },
    review_fraud: {
      relevant_laws: ['Competition Act s.74.01 (misleading representations)', 'Consumer Protection Act 2002 (Ontario)', 'Electronic Commerce Act 2000 (Ontario)'],
      reporting_bodies: ['Competition Bureau Canada', 'Google Business Profile enforcement', 'Trustpilot Fraud Team', 'Better Business Bureau'],
      standard_refs: ['FTC Endorsement Guidelines (US reference)', 'ASC (Advertising Standards Canada) Code'],
      evidence_required: ['Review export with timestamps', 'Reviewer profile screenshots', 'IP address logs if available'],
    },
    influencer_fraud: {
      relevant_laws: ['Competition Act s.74.01', 'ASC Canadian Code of Advertising Standards', 'CASL (if email involved)'],
      reporting_bodies: ['Competition Bureau Canada', 'Advertising Standards Canada', 'Platform integrity teams (Meta, TikTok, YouTube)'],
      standard_refs: ['ASC Influencer Marketing Guidelines 2024', 'IAB Canada Influencer Measurement Framework'],
      evidence_required: ['Engagement rate screenshots', 'Follower audit third-party reports', 'Contract and payment records'],
    },
    ad_fraud: {
      relevant_laws: ['Competition Act s.74.01', 'Criminal Code s.380', 'Electronic Transactions Act'],
      reporting_bodies: ['Competition Bureau Canada', 'TAG Fraud Council', 'IAB Tech Lab Transparency Center', 'Ad platform fraud teams'],
      standard_refs: ['MRC Invalid Traffic Standards', 'JICWEBS Digital Trading Standards', 'TAG Certified Against Fraud Program'],
      evidence_required: ['Campaign performance exports', 'Server access logs', 'Pixel fire logs', 'Domain/IP reputation reports'],
    },
    gov_fraud: {
      relevant_laws: [
        'Criminal Code s.380 (Fraud)', 'Criminal Code s.465 (Conspiracy)', 'Competition Act s.45 (Bid rigging)',
        'Corruption of Foreign Public Officials Act', 'Public Works and Government Services Canada Act',
      ],
      reporting_bodies: [
        'RCMP Commercial Crime Unit (rcmp-grc.gc.ca)', 'Competition Bureau — Cartels Directorate',
        'CRA Criminal Investigations', 'Auditor General of Canada', 'Ontario Auditor General',
        'Ontario Provincial Police Financial Crimes Unit', 'Public Sector Integrity Commissioner',
      ],
      standard_refs: ['Treasury Board Directive on Payments', 'Government Contract Regulations', 'Public Services Procurement Canada guidelines'],
      evidence_required: ['Contract documentation', 'Procurement records', 'Corporate registry searches', 'Bank records (via court order)', 'Correspondence'],
    },
  };

  return contexts[engine] || {
    relevant_laws: ['Competition Act (Canada)', 'Criminal Code s.380'],
    reporting_bodies: ['Competition Bureau Canada', 'RCMP'],
    standard_refs: [],
    evidence_required: ['All available documentation'],
  };
}

// ── HTML report generator ────────────────────────────────────────────────────

function generateHTMLReport(pkg) {
  const severityColor = { CRITICAL: '#E53E3E', HIGH: '#D4A017', MEDIUM: '#4A9EE5', LOW: '#2ECC71', CLEAN: '#2ECC71' };
  const color = severityColor[pkg.fraud_summary.severity] || '#888';

  const findingsHTML = pkg.findings.map(f => `
    <div style="border-left:3px solid ${severityColor[f.severity] || '#888'};padding:12px 16px;margin-bottom:12px;background:#18221C;border-radius:0 4px 4px 0">
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
        <span style="background:${severityColor[f.severity] || '#888'}22;color:${severityColor[f.severity] || '#888'};padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700">${f.severity}</span>
        <strong style="color:#E5E4E2;font-size:13px">Finding #${f.finding_number}: ${f.type?.replace(/_/g, ' ')}</strong>
      </div>
      <p style="color:#D4D8D5;font-size:12px;margin:0 0 6px">${f.description || ''}</p>
      ${f.affected_count !== undefined ? `<span style="color:#6B7C72;font-size:11px">Affected: ${f.affected_count} records</span>` : ''}
    </div>`).join('');

  const lawsHTML = (pkg.regulatory_context.relevant_laws || []).map(l => `<li style="color:#D4D8D5;font-size:12px;margin-bottom:4px">${l}</li>`).join('');
  const bodiesHTML = (pkg.regulatory_context.reporting_bodies || []).map(b => `<li style="color:#D4D8D5;font-size:12px;margin-bottom:4px">${b}</li>`).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>VIGILAX Evidence Package — ${pkg.package_id}</title>
<style>
  body{background:#0A0A0A;color:#D4D8D5;font-family:'SF Mono','Fira Code',monospace;font-size:13px;margin:0;padding:0}
  .page{max-width:900px;margin:0 auto;padding:40px 32px}
  .header{border-bottom:2px solid #C9A227;padding-bottom:24px;margin-bottom:32px}
  .logo{font-size:22px;font-weight:700;color:#C9A227;letter-spacing:2px}
  .doc-id{font-size:11px;color:#6B7C72;margin-top:4px}
  .section{margin-bottom:32px}
  .section-title{font-size:11px;text-transform:uppercase;letter-spacing:2px;color:#6B7C72;border-bottom:1px solid #1F3028;padding-bottom:8px;margin-bottom:16px;font-weight:700}
  .verdict-box{background:#18221C;border:1px solid ${color};border-radius:6px;padding:20px;display:flex;gap:32px;align-items:center;margin-bottom:24px}
  .score-circle{width:80px;height:80px;border-radius:50%;border:3px solid ${color};display:flex;align-items:center;justify-content:center;flex-direction:column;flex-shrink:0}
  .score-num{font-size:24px;font-weight:700;color:${color}}
  .score-label{font-size:9px;color:#6B7C72;text-transform:uppercase}
  .verdict-text{font-size:20px;font-weight:700;color:${color};letter-spacing:1px}
  .verdict-engine{font-size:11px;color:#6B7C72;margin-top:4px}
  .meta-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
  .meta-item{background:#18221C;border:1px solid #1F3028;border-radius:4px;padding:12px}
  .meta-label{font-size:10px;color:#6B7C72;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px}
  .meta-value{font-size:13px;color:#E5E4E2}
  .hash-box{background:#111813;border:1px solid #1F3028;border-radius:4px;padding:10px 14px;font-size:10px;color:#6B7C72;word-break:break-all;margin-top:8px}
  .action-box{background:#14573F22;border:1px solid #14573F;border-radius:6px;padding:16px;margin-top:16px}
  .action-label{font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#2ECC71;margin-bottom:6px;font-weight:700}
  .action-text{font-size:13px;color:#E5E4E2}
  .disclaimer{background:#1F3028;border-radius:4px;padding:14px;font-size:10px;color:#6B7C72;margin-top:32px;line-height:1.6}
  ul{padding-left:18px;margin:0}
  @media print{body{background:#fff;color:#000}.section-title{color:#333}.meta-item,.hash-box,.action-box,.verdict-box{border-color:#ccc;background:#f9f9f9}}
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="logo">VIGILAX SENTINEL</div>
    <div class="doc-id">Evidence Package ID: ${pkg.package_id} | Generated: ${pkg.generated_at} | Classification: CONFIDENTIAL</div>
    <div class="doc-id" style="margin-top:4px">Francisco Holdings Inc. | Authorized Investigation Report</div>
  </div>

  <div class="section">
    <div class="section-title">Fraud Assessment Summary</div>
    <div class="verdict-box">
      <div class="score-circle"><div class="score-num">${pkg.fraud_summary.risk_score}</div><div class="score-label">Risk</div></div>
      <div>
        <div class="verdict-text">${pkg.fraud_summary.verdict}</div>
        <div class="verdict-engine">Engine: ${pkg.fraud_summary.engine} | Severity: ${pkg.fraud_summary.severity}</div>
        <div style="margin-top:8px;font-size:12px;color:#D4D8D5">${pkg.fraud_summary.total_findings} finding(s): ${pkg.fraud_summary.critical_findings} critical, ${pkg.fraud_summary.high_findings} high</div>
      </div>
    </div>
    <div class="action-box">
      <div class="action-label">Recommended Action</div>
      <div class="action-text">${pkg.fraud_summary.recommended_action || '—'}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Case Information</div>
    <div class="meta-grid">
      <div class="meta-item"><div class="meta-label">Case ID</div><div class="meta-value">${pkg.case_information.case_id}</div></div>
      <div class="meta-item"><div class="meta-label">Investigator</div><div class="meta-value">${pkg.case_information.investigator}</div></div>
      <div class="meta-item"><div class="meta-label">Client</div><div class="meta-value">${pkg.case_information.client_name || 'Confidential'}</div></div>
      <div class="meta-item"><div class="meta-label">Jurisdiction</div><div class="meta-value">${pkg.case_information.jurisdiction}</div></div>
    </div>
    ${pkg.case_information.notes ? `<div class="hash-box" style="margin-top:12px"><strong>Notes:</strong> ${pkg.case_information.notes}</div>` : ''}
  </div>

  <div class="section">
    <div class="section-title">Chain of Custody</div>
    ${pkg.chain_of_custody.chain.map(step => `
      <div style="display:flex;gap:14px;margin-bottom:10px;align-items:flex-start">
        <div style="background:#C9A227;color:#0A0A0A;width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:700;flex-shrink:0">${step.step}</div>
        <div>
          <div style="font-size:12px;font-weight:700;color:#E5E4E2">${step.action}</div>
          <div style="font-size:11px;color:#6B7C72">${step.actor} | ${step.timestamp}</div>
          <div class="hash-box">SHA-256: ${step.hash}</div>
        </div>
      </div>`).join('')}
  </div>

  <div class="section">
    <div class="section-title">Findings (${pkg.findings.length})</div>
    ${findingsHTML || '<p style="color:#6B7C72">No findings recorded.</p>'}
  </div>

  <div class="section">
    <div class="section-title">Regulatory Context</div>
    <div class="meta-grid">
      <div>
        <div class="meta-label" style="margin-bottom:8px">Applicable Laws</div>
        <ul>${lawsHTML}</ul>
      </div>
      <div>
        <div class="meta-label" style="margin-bottom:8px">Reporting Bodies</div>
        <ul>${bodiesHTML}</ul>
      </div>
    </div>
    ${pkg.regulatory_context.evidence_required ? `
      <div style="margin-top:16px">
        <div class="meta-label" style="margin-bottom:8px">Evidence Required for Filing</div>
        <ul>${(pkg.regulatory_context.evidence_required || []).map(e => `<li style="color:#D4D8D5;font-size:12px;margin-bottom:4px">${e}</li>`).join('')}</ul>
      </div>` : ''}
  </div>

  <div class="disclaimer">
    <strong style="color:#C9A227">DISCLAIMER:</strong> ${pkg.disclaimer}<br><br>
    Evidence Integrity Hash: <span style="color:#E5E4E2">${pkg.chain_of_custody.evidence_integrity_hash}</span>
  </div>
</div>
</body>
</html>`;
}

// ── Law enforcement format ────────────────────────────────────────────────────

function generateLEReport(pkg) {
  const linesep = '═'.repeat(70);
  const sep     = '─'.repeat(70);
  const lines = [
    linesep,
    `VIGILAX SENTINEL — FRAUD INVESTIGATION REPORT`,
    `Francisco Holdings Inc. | Authorized Disclosure`,
    linesep,
    ``,
    `DOCUMENT CLASS:    OFFICIAL INVESTIGATION REPORT`,
    `PACKAGE ID:        ${pkg.package_id}`,
    `GENERATED:         ${pkg.generated_at}`,
    `INTEGRITY HASH:    ${pkg.chain_of_custody.evidence_integrity_hash}`,
    `JURISDICTION:      ${pkg.case_information.jurisdiction}`,
    ``,
    sep,
    `SECTION 1 — FRAUD ASSESSMENT`,
    sep,
    `Engine:            ${pkg.fraud_summary.engine?.toUpperCase()}`,
    `Verdict:           ${pkg.fraud_summary.verdict}`,
    `Risk Score:        ${pkg.fraud_summary.risk_score} / 100`,
    `Severity:          ${pkg.fraud_summary.severity}`,
    `Total Findings:    ${pkg.fraud_summary.total_findings}`,
    `Critical:          ${pkg.fraud_summary.critical_findings}`,
    `High:              ${pkg.fraud_summary.high_findings}`,
    ``,
    `Recommended Action:`,
    `  ${pkg.fraud_summary.recommended_action}`,
    ``,
    sep,
    `SECTION 2 — CASE INFORMATION`,
    sep,
    `Case ID:           ${pkg.case_information.case_id}`,
    `Investigator:      ${pkg.case_information.investigator}`,
    `Client:            ${pkg.case_information.client_name || 'CONFIDENTIAL'}`,
    pkg.case_information.notes ? `Notes:             ${pkg.case_information.notes}` : null,
    ``,
    sep,
    `SECTION 3 — CHAIN OF CUSTODY`,
    sep,
    ...pkg.chain_of_custody.chain.map(s =>
      `Step ${s.step}: ${s.action}\n  Actor: ${s.actor}\n  Time:  ${s.timestamp}\n  Hash:  ${s.hash}`
    ),
    ``,
    sep,
    `SECTION 4 — FINDINGS`,
    sep,
    ...pkg.findings.map(f =>
      `[${f.finding_number}] ${f.severity} — ${f.type}\n  ${f.description || ''}\n  Affected: ${f.affected_count || '—'} records`
    ),
    ``,
    sep,
    `SECTION 5 — APPLICABLE LAW`,
    sep,
    ...(pkg.regulatory_context.relevant_laws || []).map(l => `  • ${l}`),
    ``,
    sep,
    `SECTION 6 — REPORTING AUTHORITIES`,
    sep,
    ...(pkg.regulatory_context.reporting_bodies || []).map(b => `  • ${b}`),
    ``,
    linesep,
    `END OF REPORT`,
    ``,
    `This report was generated by VIGILAX automated analysis software.`,
    `All findings must be independently verified before use in legal proceedings.`,
    linesep,
  ].filter(l => l !== null);

  return lines.join('\n');
}

module.exports = { buildEvidencePackage, generateHTMLReport, generateLEReport, hashEvidence };
